CREATE DATABASE "UrlShortener_Dev" WITH OWNER = postgres ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' CONNECTION
LIMIT = -1 TEMPLATE = template0;
CREATE SCHEMA IF NOT EXISTS dbo;
CREATE TABLE IF NOT EXISTS dbo.tbl_UrlMappings (
	Id SERIAL PRIMARY KEY,
	OriginalUrl TEXT NOT NULL CHECK (length(OriginalUrl) > 0),
	ShortCode VARCHAR(20) UNIQUE,
	CreatedDateTimeUtc TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_urlmappings_shortcode ON dbo.tbl_UrlMappings(ShortCode);