CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE IF NOT EXISTS dbo.tbl_UrlMappings (
Id SERIAL PRIMARY KEY,
OriginalUrl TEXT NOT NULL,
ShortCode VARCHAR(20) NULL,
CreatedDateTimeUtc TIMESTAMP NOT NULL
)