# Use Node.js base image
FROM node:22

# Set working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy compiled output
COPY dist ./dist

# Expose port
EXPOSE 3000

# Start the app
CMD ["node", "dist/index.js"]
