name: Build and deploy Node.js project to Azure Function App - ShortLnk

on:
    push:
        branches:
            - main

env:
    AZURE_FUNCTIONAPP_PACKAGE_PATH: "url-shortener-api"
    NODE_VERSION: "22.x"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node ${{ env.NODE_VERSION }} Environment
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install, Lint, and Build
              run: |
                  pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
                  npm ci
                  npm run lint
                  npm run build
                  popd

            - name: Zip artifact for deployment
              run: zip -r release.zip '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact
              run: |
                  unzip release.zip
                  rm release.zip

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7383BD9B8F6246EEADB11660CF10A80B }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5B2E8C5F4998441C9D7BC426BBE6A199 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5B0F568EF74B4D10A11582F99DFD085C }}

            - name: Deploy to Azure Function App
              uses: Azure/functions-action@v1
              with:
                  app-name: "ShortLnk"
                  slot-name: "Production"
                  package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
