name: Deploy UI

on:
    push:
        branches:
            - main
        paths:
            - "url-shortener-ui/**"
            - ".github/workflows/deploy-ui.yaml"

    workflow_dispatch:

env:
    UI_LOCATION: "url-shortener-ui"
    OUTPUT_LOCATION: "url-shortener-ui/dist/url-shortener-ui/browser"
    CONFIG_FILE: "src/assets/config.json"

jobs:
    build:
        name: Build UI
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  submodules: true
                  lfs: false

            - name: Setup Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm"
                  cache-dependency-path: ${{ env.UI_LOCATION }}/package-lock.json

            - name: Install Dependencies
              run: npm ci
              working-directory: ${{ env.UI_LOCATION }}

            - name: Lint Project
              run: npm run lint
              working-directory: ${{ env.UI_LOCATION }}

            - name: Inject Runtime Config from GitHub Secrets
              run: |
                  sed -i "s|#API_BASE_URL#|${{ secrets.PROD_API_BASE_URL }}|g" "${{ env.UI_LOCATION }}/${{ env.CONFIG_FILE }}"
                  # Add more keys here as needed

            - name: Build for Production
              run: npm run build:prod
              working-directory: ${{ env.UI_LOCATION }}

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ui-artifact
                  path: ${{ env.OUTPUT_LOCATION }}

    deploy:
        name: Deploy UI to Azure
        runs-on: ubuntu-latest
        needs: build
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: ui-artifact
                  path: ui-artifact

            - name: Deploy to Azure Static Web App
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_SMOKE_083453700 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: "upload"
                  app_location: ui-artifact
                  api_location: ""
                  output_location: ""
                  skip_app_build: true
