name: Deploy API

on:
    push:
        branches:
            - main
        paths:
            - "url-shortener-api/**"
            - ".github/workflows/deploy-api.yaml"

    workflow_dispatch:

env:
    API_DIR_PATH: "url-shortener-api"
    NODE_VERSION: "22.x"

jobs:
    build:
        name: Build API
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Dependencies
              run: npm ci
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Lint Project
              run: npm run lint
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Build Project
              run: npm run build
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Package Build Artifact
              run: |
                  zip -r release.zip dist package.json package-lock.json host.json prisma
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: api-artifact
                  path: ${{ env.API_DIR_PATH }}/release.zip

    migrate:
        name: Run Database Migrations
        runs-on: ubuntu-latest
        needs: build
        env:
            DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Dependencies
              run: npm ci
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Run Prisma Migrations
              run: npx prisma migrate deploy
              working-directory: ${{ env.API_DIR_PATH }}
              env:
                  DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

    deploy:
        name: Deploy API to Azure
        runs-on: ubuntu-latest
        needs: migrate
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: api-artifact
                  path: api-artifact

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "shortlnkr"
                  package: api-artifact/release.zip
