name: Build and Deploy API with DB Migration

on:
    push:
        branches: [main]
        paths:
            - "url-shortener-api/**"
            - ".github/workflows/deploy-api.yaml"
    workflow_dispatch:

env:
    API_DIR_PATH: "url-shortener-api"
    NODE_VERSION: "22.x"

jobs:
    build:
        name: Build API
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Dependencies
              run: npm ci
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Lint Project
              run: npm run lint
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Build Project
              run: npm run build
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Package Build Artifact
              run: zip -r release.zip dist package.json package-lock.json prisma
              working-directory: ${{ env.API_DIR_PATH }}

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: api-artifact
                  path: ${{ env.API_DIR_PATH }}/release.zip

    migrate:
        name: Run Database Migrations
        runs-on: ubuntu-latest
        needs: build
        env:
            DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: api-artifact
                  path: api-artifact

            - name: Extract Artifact
              run: unzip api-artifact/release.zip -d api-artifact

            - name: Install Dependencies for Migration
              run: npm ci
              working-directory: api-artifact

            - name: Run Prisma Migrations
              run: npx prisma migrate deploy
              working-directory: api-artifact
              env:
                  DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

    deploy:
        name: Deploy API to Azure Web App
        runs-on: ubuntu-latest
        needs: migrate
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: api-artifact
                  path: api-artifact

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "shortlnkr"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E0FE18A1C280411295DEC490EF304718 }}
                  package: api-artifact/release.zip
