name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
#Environment variables at the workflow level
env:
  UI_LOCATION: "/url-shortener-ui"
  OUTPUT_LOCATION: "/url-shortener-ui/dist/url-shortener-ui"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: .${{ env.UI_LOCATION }}/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: .${{ env.UI_LOCATION }}

      - name: Lint project
        run: npm run lint
        working-directory: .${{ env.UI_LOCATION }}

      - name: Build for production
        run: npm run build:prod
        working-directory: .${{ env.UI_LOCATION }}
      
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_UI_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.UI_LOCATION }} # App source code path
          api_location: "" # Api source code path - optional
          output_location: ${{ env.OUTPUT_LOCATION }} # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_UI_DEPLOYMENT_TOKEN }}
          action: "close"
